### ISSUE TITLE
composer packagist setup

### ISSUE THREAD

**Issue by mandrew** [pattern-lab/edition-php-thin#2]
Has this composer project been set up on packagist? If composer can't find the files in the current directory then it goes off to packagist to find it but it came back with an error for me.

composer show pattern-lab/framework-thin-edition
No composer.json found in the current directory, showing available packages from packagist
                                                        
[InvalidArgumentException]                            
Package pattern-lab/framework-thin-edition not found

**Comment by dmolsen** [comment]
@mandrew -

I had the wrong name in the README. I ended up calling it `pattern-lab/edition-thin` on packagist. I've updated the README with the correct install directions. Note that the thin edition is basically useless out of the box. It's meant to be the starting point for a Yeoman generator-like project. If you're working on that kind of thing then let me know :)

Also, here's a [breakdown of the various bits](https://github.com/pattern-lab/edition-php-thin/issues/1#issuecomment-49741385) that make up an edition in PL2.
